feat: show currency and loan product name when displaying savings pro…
one-acre-fund/fineract-frontend-v2 pull request #132
Opened 2024-06-14 13:45 UTC by gilclefes

## Description
[SER-2735] - show currency and loan product name when displaying savings products in list, view and edit view.

## Changes Included in PR
- https://oneacrefund.atlassian.net/browse/SER-2735

## PR Checklist
- [ ] Xray tests created
- [ ] PM tested and approved
- [ ] Read and understood the contribution guidelines at `web-app/.github/CONTRIBUTING.md`

## Screenshots, if any
<img width="897" alt="image" src="https://github.com/one-acre-fund/fineract-frontend-v2/assets/124994/fb5f53a9-aeed-4e8d-905c-90ad6499ac7e">

.

[SER-2735]: https://oneacrefund.atlassian.net/browse/SER-2735?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

2024-06-14 13:47 UTC, oneacrefund-automation commented
## [🦙 MegaLinter](https://megalinter.io/7.12.0) status: ✅ SUCCESS

|Descriptor |                                    Linter                                    |Files|Fixed|Errors|Elapsed time|
|-----------|------------------------------------------------------------------------------|----:|-----|-----:|------------|
|✅ HTML    |[htmlhint](https://megalinter.io/7.12.0/descriptors/html_htmlhint)            |    2|     |     0|0.3s        |
|✅ MARKDOWN|[markdownlint](https://megalinter.io/7.12.0/descriptors/markdown_markdownlint)|    1|     |     0|0.34s       |

See detailed report in MegaLinter reports
_Set `VALIDATE_ALL_CODEBASE: true` in mega-linter.yml to validate all sources, not only the diff_

_MegaLinter is graciously provided by [![OX Security](https://www.ox.security/wp-content/uploads/2022/06/logo.svg?ref=megalinter_comment)](https://www.ox.security/?ref=megalinter)_

<!-- megalinter: github-comment-reporter -->

2024-06-14 15:05 UTC, amydoxym submitted a review, later dismissed

2024-06-14 15:56 UTC, amydoxym submitted a review, later dismissed

2024-06-18 06:43 UTC, Vikeln requested changes

2024-06-18 06:43 UTC, Vikeln commented on src/app/products/saving-products/saving-product-stepper/saving-product-details-step/saving-product-details-step.component.ts
> +      console.log('gilbert islinked ' + this.isLinkedToLoanProduct);
Please remove these logs

2024-06-18 09:51 UTC, gilclefes commented on src/app/products/saving-products/saving-product-stepper/saving-product-details-step/saving-product-details-step.component.ts
> +      console.log('gilbert islinked ' + this.isLinkedToLoanProduct);
done @Vikeln

2024-06-19 06:48 UTC, shejasabin approved these changes

2024-06-19 07:32 UTC, amydoxym approved these changes

2024-06-19 07:45 UTC, merged