SER-2902 Disable loan submit button for 5 seconds to avoid double clicks
one-acre-fund/fineract-frontend-v2 pull request #184
Opened 2024-08-08 11:02 UTC by simiyu17

## Description
Disable loan submit button for 5 seconds to avoid double clicks

## Changes Included in PR
- Jira Ticket : [https://oneacrefund.atlassian.net/browse/SER-2893](https://oneacrefund.atlassian.net/browse/SER-2893)

## PR Checklist
- [ ] Xray tests created
- [ ] PM tested and approved
- [ ] Read and understood the contribution guidelines at `web-app/.github/CONTRIBUTING.md`

## Screenshots, if any

.

2024-08-08 11:14 UTC, gilclefes commented on src/app/loans/loans-account-stepper/loans-account-preview-step/loans-account-preview-step.component.ts
> +      this.isLoanSubmitButtonDisabled = false;
Can we add value as environment variable, they should also be added to the env.js and eve.template.js so we can update them from docker.

2024-08-08 18:23 UTC, gilclefes approved these changes
looks good to me

2024-08-09 08:25 UTC, amydoxym requested changes
nice Implementation..just update the release notes as suggested

2024-08-09 08:25 UTC, amydoxym commented on RELEASE_NOTES.md
> +    * [SER-2902] - Disable loan submit button for 5 seconds to avoid double clicks.
```suggestion
    * [SER-2902] - Disable loan submit button for a specific period to avoid double clicks.
```

2024-08-09 08:43 UTC, simiyu17 commented on RELEASE_NOTES.md
> +    * [SER-2902] - Disable loan submit button for 5 seconds to avoid double clicks.
@amydoxym  Done

2024-08-09 08:54 UTC, amydoxym approved these changes

2024-08-09 09:03 UTC, merged