feat: SER-2664 show only client eligible lp
one-acre-fund/fineract-frontend-v2 pull request #185
Opened 2024-08-09 12:33 UTC by shejasabin

## Description
Updated to only display client eligible loan product

2024-08-13 13:36 UTC, gilclefes approved these changes
looks good to me.

2024-08-16 07:20 UTC, amydoxym requested changes

2024-08-16 07:20 UTC, amydoxym commented on package.json
> +  "version": "1.3.4",
@shejasabin  1.3.3 is still the next release, so you can revert this

2024-08-19 08:34 UTC, amydoxym approved these changes

2024-08-19 08:35 UTC, merged