SER-1517 component created for loan allocation products
one-acre-fund/fineract-frontend-v2 pull request #44
Opened 2023-02-09 10:05 UTC by SauravPriyadarshy

The whole loan allocation protocol involves the list view, the add view as currently implemented and visible in loans.test. Implemented all screens for the loan allocation process.

## Related issues and discussion
#{Issue Number}

## Screenshots, if any
![image](https://user-images.githubusercontent.com/108924123/217781353-4179f09a-9afc-4ee7-9bba-bf9d8da09b9b.png)
![image](https://user-images.githubusercontent.com/108924123/217781449-a9aa683a-d73c-4f7b-b3c6-37b96b2ed36e.png)

2023-02-09 11:53 UTC, william000000 requested changes

2023-02-09 11:53 UTC, william000000 commented on src/app/products/loan-product-allocation-setting/loan-product-allocation-setting.component.html
> +      <fa-icon icon="plus"></fa-icon>&nbsp;&nbsp;
The permission should be `CREATE_LOANPAYMENTALLOCATIONSETTING`

2023-02-09 11:57 UTC, william000000 commented on src/app/products/products.component.html
>              <p matLine>Add new loan product or modify or inactivate loan product</p>
I think the title was already correct

2023-02-09 11:57 UTC, william000000 commented on src/app/products/products.component.html
> +            <mat-icon matListIcon>
And it would be `READ_LOANPAYMENTALLOCATIONSETTING`

2023-02-13 06:12 UTC, gilclefes approved these changes
looks good to me.

2023-02-13 06:57 UTC, william000000 approved these changes
Lgtm

2023-02-13 07:45 UTC, merged